### ISSUE TITLE
support for prisma2?

### ISSUE THREAD

**Issue by macrozone** [UnlyEd/ra-data-graphql-prisma#6]
hi there!

i am unsure about the difference between the generated graphql api from prisma1 and prisma2 (both nexus-prisma) so i am unsure if this dataprovider already supports prisma2. Anyone has experience with it?

**Comment by Vadorequest** [comment]
I can't tell, I've never used Prisma myself.

My real goal is was to support GraphCMS, which uses Prisma v1. See https://docs.graphcms.com/docs/introduction/

But they have removed Prisma from their tech stack and built their own thing, which will be released in the upcoming "Next" version. See https://graphcms.com/docs

**Comment by macrozone** [comment]
@Vadorequest thank you, nevermind, i managed to adopt one for prisma2 and we plan to release it on github soon.

**Comment by Vadorequest** [comment]
@macrozone Would you mind to share its url when it's done? I may be interested in the future :)

**Comment by macrozone** [comment]
@Vadorequest sure! 

@claudiocro we should not forget ;-)

**Comment by macrozone** [comment]
i'll reopen for the moment so i can add a todo

**Comment by macrozone** [comment]
We released our first version! Check it out here: https://github.com/panter/ra-data-prisma

its testdriven and tests are written against an actual prisma/nexus introspection result. This makes sure that its compatible to nexus. 

it comes with an additional package for the backend (nexus) that will create the needed resolvers
